#!/bin/sh
yarn fmt

. "$(dirname "$0")/_/husky.sh"

echo "Running tests before push..."
export DATABASE_URL="postgresql://root:1234ewq1@localhost:5432/test_db?schema=public"
npx prisma migrate reset --force --skip-seed

# yarn test --run

if [ $? -ne 0 ]; then
  echo "❌ Tests failed. Push aborted."
  exit 1
fi

echo "✅ Tests passed. Proceeding with push."
